from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

import pandas as pd
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile, status
from sqlalchemy.orm import Session

from db.session import get_db_session
from repositories.commit_files_repository import (
    COMMIT_FILES_COLUMNS,
    CommitFilesRepository,
)
from schemas.commit_files import (
    BOOL_FIELDS,
    DATETIME_FIELDS,
    DEFAULT_COMMIT_FILES_VALUES,
    INT_FIELDS,
    REQUIRED_FIELDS,
    CommitFilesImportResponse,
)
from utils.csv_loader import read_uploaded_csv
from utils.parsers import coerce_bool, coerce_datetime, coerce_int, sanitize_value

router = APIRouter(prefix="/commit-files", tags=["commit-files"])
_repository = CommitFilesRepository()


def _prepare_rows(df: pd.DataFrame) -> List[Dict]:
    # Skip 'id' column - it will be auto-generated by the database
    SKIPPED_COLUMNS = {"id"}
    
    missing_columns = [col for col in REQUIRED_FIELDS if col not in df.columns]
    if missing_columns:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"CSV missing required columns: {', '.join(missing_columns)}",
        )

    prepared: List[Dict] = []

    records = df.to_dict(orient="records")
    for idx, record in enumerate(records, start=1):
        try:
            row: Dict[str, Any] = {}
            for column in COMMIT_FILES_COLUMNS:
                # Skip columns that should not be processed from CSV
                if column in SKIPPED_COLUMNS:
                    continue
                    
                raw_value = sanitize_value(
                    record.get(column, DEFAULT_COMMIT_FILES_VALUES.get(column))
                )

                if column in INT_FIELDS and raw_value is not None:
                    raw_value = coerce_int(raw_value, strict=True)
                elif column in BOOL_FIELDS and raw_value is not None:
                    raw_value = coerce_bool(raw_value)
                elif column in DATETIME_FIELDS and raw_value is not None:
                    raw_value = coerce_datetime(raw_value, strict=True)

                row[column] = raw_value

            for field in REQUIRED_FIELDS:
                if row.get(field) is None:
                    raise ValueError(f"Missing required value for '{field}'")

            now = datetime.utcnow()
            row["createddate"] = row.get("createddate") or now
            row["modifieddate"] = row.get("modifieddate") or now

            prepared.append(row)
        except ValueError:
            continue

    return prepared


@router.post(
    "/csv",
    status_code=status.HTTP_201_CREATED,
    summary="Import commit files from a CSV file",
    response_model=CommitFilesImportResponse,
)
async def import_commit_files_from_csv(
    file: UploadFile = File(...),
    session: Session = Depends(get_db_session),
) -> CommitFilesImportResponse:
    df = await read_uploaded_csv(file)

    rows = _prepare_rows(df)
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No valid commit file rows found in CSV.",
        )

    inserted = _repository.bulk_insert(session, rows)
    # bulk_insert now returns [{"inserted_count": N}] due to COPY optimization
    inserted_count = inserted[0].get("inserted_count", 0) if inserted else 0
    return CommitFilesImportResponse(
        rows_received=len(df),
        rows_inserted=inserted_count,
        rows_skipped=len(df) - len(rows),  # rows that failed validation
        commit_files=inserted,
    )
