from typing import List, Dict, Any
from sqlalchemy.orm import Session
from sqlalchemy import text
import json
from repositories.bulk_copy import bulk_copy_insert_jira


class JiraImportRepository:
    """Repository for JIRA data imports using SQLAlchemy"""

    def import_boards(self, session: Session, boards: List[Dict[str, Any]], org_id: int, user_integration_id: int = None) -> Dict[str, Any]:
        """
        Import boards into insightly_jira.board table
        Note: 'id' and 'created_at' are auto-generated by database
        """
        try:
            if not boards:
                return {"success": True, "inserted_count": 0, "inserted_records": []}
            
            inserted_records = []
            
            for board in boards:
                query = text("""
                    INSERT INTO insightly_jira.board (
                        account_id, active, avatar_uri, display_name, entity_id,
                        is_private, jira_board_id, board_key, name, org_id,
                        self, uuid, is_deleted, auto_generated_sprint, azure_project_id,
                        azure_project_name, azure_org_name, last_issue_update_time,
                        has_permission, valid, board_type, modifieddate
                    ) VALUES (
                        :account_id, :active, :avatar_uri, :display_name, :entity_id,
                        :is_private, :jira_board_id, :board_key, :name, :org_id,
                        :self, :uuid, :is_deleted, :auto_generated_sprint, :azure_project_id,
                        :azure_project_name, :azure_org_name, :last_issue_update_time,
                        :has_permission, :valid, :board_type, NOW()
                    )
                    RETURNING id, jira_board_id, name
                """)
                
                params = {
                    'account_id': board.get('account_id'),
                    'active': board.get('active'),
                    'avatar_uri': board.get('avatar_uri'),
                    'display_name': board.get('display_name'),
                    'entity_id': board.get('entity_id'),
                    'is_private': board.get('is_private'),
                    'jira_board_id': board.get('jira_board_id'),
                    'board_key': board.get('board_key'),
                    'name': board.get('name'),
                    'org_id': org_id,
                    'self': board.get('self'),
                    'uuid': board.get('uuid'),
                    'is_deleted': board.get('is_deleted', False),
                    'auto_generated_sprint': board.get('auto_generated_sprint', False),
                    'azure_project_id': board.get('azure_project_id'),
                    'azure_project_name': board.get('azure_project_name'),
                    'azure_org_name': board.get('azure_org_name'),
                    'last_issue_update_time': board.get('last_issue_update_time'),
                    'has_permission': board.get('has_permission'),
                    'valid': board.get('valid'),
                    'board_type': board.get('board_type')
                }
                
                result = session.execute(query, params)
                record = result.fetchone()
                if record:
                    inserted_records.append({
                        "id": record[0],
                        "jira_board_id": record[1],
                        "name": record[2]
                    })
            
            return {
                "success": True,
                "inserted_count": len(inserted_records),
                "inserted_records": inserted_records
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing boards: {str(e)}")

    def import_jira_sub_boards(self, session: Session, sub_boards: List[Dict[str, Any]], org_id: int, user_integration_id: int = None) -> Dict[str, Any]:
        """
        Import jira sub boards into insightly_jira.jira_sub_board table
        Note: Only 'id' is auto-generated by database (IDENTITY)
        """
        try:
            inserted_records = []
            
            for sub_board in sub_boards:
                query = text("""
                    INSERT INTO insightly_jira.jira_sub_board (
                        board_id, jira_board_id, sub_board_id, name, type,
                        organizationid, is_deleted, jql, modifieddate
                    ) VALUES (
                        :board_id, :jira_board_id, :sub_board_id, :name, :type,
                        :organizationid, :is_deleted, :jql, NOW()
                    )
                    RETURNING id, sub_board_id, name
                """)
                
                params = {
                    'board_id': sub_board.get('board_id'),
                    'jira_board_id': sub_board.get('jira_board_id'),
                    'sub_board_id': sub_board.get('sub_board_id'),
                    'name': sub_board.get('name'),
                    'type': sub_board.get('type'),
                    'organizationid': org_id,
                    'is_deleted': sub_board.get('is_deleted', False),
                    'jql': sub_board.get('jql')
                }
                
                result = session.execute(query, params)
                record = result.fetchone()
                if record:
                    inserted_records.append({
                        "id": record[0],
                        "sub_board_id": record[1],
                        "name": record[2]
                    })
            
            session.commit()
            
            return {
                "success": True,
                "inserted_count": len(inserted_records),
                "inserted_records": inserted_records
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing jira sub boards: {str(e)}")

    def import_sprints(self, session: Session, sprints: List[Dict[str, Any]], org_id: int, user_integration_id: int = None) -> Dict[str, Any]:
        """
        Import sprints into insightly_jira.sprint table
        Note: 'id' and 'created_at' are auto-generated by database
        """
        try:
            inserted_records = []
            
            for sprint in sprints:
                query = text("""
                    INSERT INTO insightly_jira.sprint (
                        is_deleted, modifieddate, board_id, complete_date, end_date,
                        goal, name, sprint_jira_id, start_date, state, org_id,
                        self_url, jira_board_id, auto_generated, azure_org_name,
                        metrics_generated, sub_board_id, type, shared_boards,
                        sprint_path, valid
                    ) VALUES (
                        :is_deleted, NOW(), :board_id, :complete_date, :end_date,
                        :goal, :name, :sprint_jira_id, :start_date, :state, :org_id,
                        :self_url, :jira_board_id, :auto_generated, :azure_org_name,
                        :metrics_generated, :sub_board_id, :type, :shared_boards,
                        :sprint_path, :valid
                    )
                    RETURNING id, sprint_jira_id, name
                """)
                
                params = {
                    'is_deleted': sprint.get('is_deleted'),
                    'board_id': sprint.get('board_id'),
                    'complete_date': sprint.get('complete_date'),
                    'end_date': sprint.get('end_date'),
                    'goal': sprint.get('goal'),
                    'name': sprint.get('name'),
                    'sprint_jira_id': sprint.get('sprint_jira_id'),
                    'start_date': sprint.get('start_date'),
                    'state': sprint.get('state'),
                    'org_id': org_id,
                    'self_url': sprint.get('self_url'),
                    'jira_board_id': sprint.get('jira_board_id'),
                    'auto_generated': sprint.get('auto_generated', False),
                    'azure_org_name': sprint.get('azure_org_name'),
                    'metrics_generated': sprint.get('metrics_generated', False),
                    'sub_board_id': sprint.get('sub_board_id'),
                    'type': sprint.get('type'),
                    'shared_boards': sprint.get('shared_boards'),
                    'sprint_path': sprint.get('sprint_path'),
                    'valid': sprint.get('valid')
                }
                
                result = session.execute(query, params)
                record = result.fetchone()
                if record:
                    inserted_records.append({
                        "id": record[0],
                        "sprint_jira_id": record[1],
                        "name": record[2]
                    })
            
            session.commit()
            
            return {
                "success": True,
                "inserted_count": len(inserted_records),
                "inserted_records": inserted_records
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing sprints: {str(e)}")

    def import_issues(self, session: Session, issues: List[Dict[str, Any]], org_id: int, user_integration_id: int = None) -> Dict[str, Any]:
        """
        Import issues into insightly_jira.issue table using high-performance COPY.
        Note: 'id' and 'created_at' are auto-generated by database
        Only inserts columns that are provided in the CSV
        """
        try:
            if not issues:
                return {"success": True, "inserted_count": 0, "inserted_records": []}
            
            # Define columns for COPY (excluding auto-generated id and created_at)
            columns = [
                'modifieddate', 'board_id', 'sprint_id', 'issue_id', 'key',
                'issue_type', 'status', 'priority', 'story_point', 'summary',
                'assignee_id', 'is_deleted', 'is_epic', 'product', 'allocation',
                'jira_create_date', 'org_id', 'parent_issue_id'
            ]
            
            # Prepare rows with defaults and org_id
            rows = []
            for issue in issues:
                row = {
                    'modifieddate': 'NOW()',  # Will be handled specially
                    'board_id': issue.get('board_id'),
                    'sprint_id': issue.get('sprint_id') or None,
                    'issue_id': issue.get('issue_id'),
                    'key': issue.get('key'),
                    'issue_type': issue.get('issue_type'),
                    'status': issue.get('status'),
                    'priority': issue.get('priority'),
                    'story_point': issue.get('story_point'),
                    'summary': issue.get('summary'),
                    'assignee_id': issue.get('assignee_id'),
                    'is_deleted': 'false' if str(issue.get('is_deleted', 'False')).lower() == 'false' else 'true',
                    'is_epic': 'true' if str(issue.get('is_epic', 'False')).lower() == 'true' else 'false',
                    'product': issue.get('product', 'Unassigned'),
                    'allocation': issue.get('allocation', 'Unallocated'),
                    'jira_create_date': issue.get('jira_create_date'),
                    'org_id': org_id,
                    'parent_issue_id': issue.get('parent_issue_id') or None,
                }
                rows.append(row)
            
            # For COPY, we need to set modifieddate separately since NOW() is a function
            # Update modifieddate column to use current timestamp string
            from datetime import datetime
            current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            for row in rows:
                row['modifieddate'] = current_time
            
            # Use bulk COPY for high-performance insert
            inserted_count = bulk_copy_insert_jira(session, 'issue', columns, rows)
            
            session.commit()
            
            # Query back the inserted records to get their IDs
            query = text("""
                SELECT id, issue_id, "key" 
                FROM insightly_jira.issue 
                WHERE org_id = :org_id 
                ORDER BY id DESC 
                LIMIT :limit
            """)
            result = session.execute(query, {'org_id': org_id, 'limit': inserted_count})
            inserted_records = [
                {"id": row[0], "issue_id": row[1], "key": row[2]}
                for row in result.fetchall()
            ]
            inserted_records.reverse()  # Restore original order
            
            return {
                "success": True,
                "inserted_count": inserted_count,
                "inserted_records": inserted_records
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing issues: {str(e)}")

    def import_sprint_issue_mappings(self, session: Session, mappings: List[Dict[str, Any]], org_id: int, user_integration_id: int = None) -> Dict[str, Any]:
        """
        Import sprint issue mappings into insightly_jira.sprint_issue_mapping table
        Note: 'id' and 'created_at' are auto-generated by database
        """
        try:
            inserted_records = []
            
            for mapping in mappings:
                query = text("""
                    INSERT INTO insightly_jira.sprint_issue_mapping (
                        modifieddate, issue_id, sprint_id, is_deleted, resolution, org_id
                    ) VALUES (
                        NOW(), :issue_id, :sprint_id, :is_deleted, :resolution, :org_id
                    )
                    RETURNING id, issue_id, sprint_id
                """)
                
                params = {
                    'issue_id': mapping.get('issue_id'),
                    'sprint_id': mapping.get('sprint_id'),
                    'is_deleted': mapping.get('is_deleted'),
                    'resolution': mapping.get('resolution'),
                    'org_id': org_id
                }
                
                result = session.execute(query, params)
                record = result.fetchone()
                if record:
                    inserted_records.append({
                        "id": record[0],
                        "issue_id": record[1],
                        "sprint_id": record[2]
                    })
            
            session.commit()
            
            return {
                "success": True,
                "inserted_count": len(inserted_records),
                "inserted_records": inserted_records
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing sprint issue mappings: {str(e)}")

    def import_team_board_mappings(self, session: Session, mappings: List[Dict[str, Any]], org_id: int, user_integration_id: int = None) -> Dict[str, Any]:
        """
        Import team board mappings into insightly.team_board_mapping table
        Note: Only 'id' is auto-generated by database
        """
        try:
            inserted_records = []
            
            for mapping in mappings:
                query = text("""
                    INSERT INTO insightly.team_board_mapping (
                        team_name, team_id, board_name, board_id, client_team_name,
                        assignment_group, organization_id, mapping_processed
                    ) VALUES (
                        :team_name, :team_id, :board_name, :board_id, :client_team_name,
                        :assignment_group, :organization_id, :mapping_processed
                    )
                    RETURNING id, team_name, board_name
                """)
                
                params = {
                    'team_name': mapping.get('team_name'),
                    'team_id': mapping.get('team_id'),
                    'board_name': mapping.get('board_name'),
                    'board_id': mapping.get('board_id'),
                    'client_team_name': mapping.get('client_team_name'),
                    'assignment_group': mapping.get('assignment_group'),
                    'organization_id': org_id,
                    'mapping_processed': mapping.get('mapping_processed', True)
                }
                
                result = session.execute(query, params)
                record = result.fetchone()
                if record:
                    inserted_records.append({
                        "id": record[0],
                        "team_name": record[1],
                        "board_name": record[2]
                    })
            
            session.commit()
            
            return {
                "success": True,
                "inserted_count": len(inserted_records),
                "inserted_records": inserted_records
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing team board mappings: {str(e)}")

    def import_issue_event_logs(self, session: Session, events: List[Dict[str, Any]], org_id: int, user_integration_id: int) -> Dict[str, Any]:
        """
        Import issue event logs into insightly_jira.issue_event_log table using high-performance COPY.
        Used for sprint metrics: planned/unplanned completed/spillover tracking
        Note: 'id' is auto-generated by database sequence
        """
        try:
            if not events:
                return {"success": True, "inserted_count": 0}
            
            # Define columns for COPY (excluding auto-generated id, created_date, modifieddate)
            columns = [
                'issue_id', 'sprint_id', 'assignee_id', 'board_id', 'issue_key',
                'status', 'resolution_date', 'issue_added_timestamp',
                'sprint_started_timestamp', 'sprint_closed_timestamp',
                'planned', 'spillover', 'deleted', 
                'org_id', 'user_integration_id', 'parent_issue_id', 'story_point',
                'original_assignee', 'old_assignee'
            ]
            
            # Prepare rows with org_id and user_integration_id
            rows = []
            for event in events:
                row = {
                    'issue_id': event.get('issue_id'),
                    'sprint_id': event.get('sprint_id'),
                    'assignee_id': event.get('assignee_id'),
                    'board_id': event.get('board_id'),
                    'issue_key': event.get('issue_key'),
                    'status': event.get('status'),
                    'resolution_date': event.get('resolution_date'),
                    'issue_added_timestamp': event.get('issue_added_timestamp'),
                    'sprint_started_timestamp': event.get('sprint_started_timestamp'),
                    'sprint_closed_timestamp': event.get('sprint_closed_timestamp'),
                    'planned': event.get('planned'),
                    'spillover': event.get('spillover'),
                    'deleted': event.get('deleted', False),
                    'org_id': org_id,
                    'user_integration_id': user_integration_id,
                    'parent_issue_id': event.get('parent_issue_id'),
                    'story_point': event.get('story_point'),
                    'original_assignee': event.get('original_assignee'),
                    'old_assignee': event.get('old_assignee')
                }
                rows.append(row)
            
            # Use bulk COPY for high-performance insert
            inserted_count = bulk_copy_insert_jira(session, 'issue_event_log', columns, rows)
            
            session.commit()
            
            return {
                "success": True,
                "inserted_count": inserted_count
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing issue event logs: {str(e)}")

    def import_jira_git_mappings(self, session: Session, mappings: List[Dict[str, Any]], org_id: int) -> Dict[str, Any]:
        """
        Import JIRA-Git activity mappings into insightly.jira_issue_git_activity_mapping table using high-performance COPY.
        Links Jira issues with Git activities (commits and pull requests).
        
        Note: 
        - 'id' is auto-generated by database sequence
        - 'activity_date' and 'actor' are fetched from commit/pull_request tables based on activity_id
        """
        try:
            if not mappings:
                return {"success": True, "inserted_count": 0}
            
            # Define columns for COPY (excluding auto-generated id)
            columns = [
                'issue_id', 'jira_issue_id', 'issue_key', 'activity_type',
                'activity_id', 'activity_date', 'actor', 'organization_id',
                'azure_issue_url', 'jira_hotfix_pr'
            ]
            
            # Collect all activity IDs by type for batch fetching
            commit_ids = []
            pr_ids = []
            for mapping in mappings:
                activity_type = mapping.get('activity_type')
                activity_id = mapping.get('activity_id')
                if activity_type in ['COMMIT', 'MERGE_COMMIT'] and activity_id:
                    # Convert to int if it's a string
                    commit_ids.append(int(activity_id) if isinstance(activity_id, str) else activity_id)
                elif activity_type == 'PULLREQUEST' and activity_id:
                    # Convert to int if it's a string
                    pr_ids.append(int(activity_id) if isinstance(activity_id, str) else activity_id)
            
            # Fetch commit data in batch
            commit_data = {}
            if commit_ids:
                commit_query = text("""
                    SELECT id, date, authorid 
                    FROM insightly.commit 
                    WHERE id = ANY(:ids) AND organizationid = :org_id
                """)
                result = session.execute(commit_query, {'ids': commit_ids, 'org_id': org_id})
                for row in result:
                    commit_data[row[0]] = {'date': row[1], 'authorid': row[2]}
            
            # Fetch pull request data in batch
            pr_data = {}
            if pr_ids:
                pr_query = text("""
                    SELECT id, createdon, authorid 
                    FROM insightly.pull_request 
                    WHERE id = ANY(:ids) AND organizationid = :org_id
                """)
                result = session.execute(pr_query, {'ids': pr_ids, 'org_id': org_id})
                for row in result:
                    pr_data[row[0]] = {'createdon': row[1], 'authorid': row[2]}
            
            # Prepare rows with fetched activity_date and actor
            rows = []
            skipped_count = 0
            for mapping in mappings:
                activity_type = mapping.get('activity_type')
                activity_id = mapping.get('activity_id')
                
                # Convert activity_id to int for lookup (CSV values are strings)
                activity_id_int = int(activity_id) if isinstance(activity_id, str) else activity_id
                
                # Fetch activity_date and actor based on activity_type
                activity_date = None
                actor = None
                
                if activity_type in ['COMMIT', 'MERGE_COMMIT']:
                    if activity_id_int in commit_data:
                        activity_date = commit_data[activity_id_int]['date']
                        actor = commit_data[activity_id_int]['authorid']
                    else:
                        skipped_count += 1
                        continue  # Skip if commit not found
                        
                elif activity_type == 'PULLREQUEST':
                    if activity_id_int in pr_data:
                        activity_date = pr_data[activity_id_int]['createdon']
                        actor = pr_data[activity_id_int]['authorid']
                    else:
                        skipped_count += 1
                        continue  # Skip if PR not found
                else:
                    skipped_count += 1
                    continue  # Skip invalid activity_type
                
                row = {
                    'issue_id': mapping.get('issue_id'),
                    'jira_issue_id': mapping.get('jira_issue_id'),
                    'issue_key': mapping.get('issue_key'),
                    'activity_type': activity_type,
                    'activity_id': activity_id,
                    'activity_date': activity_date,
                    'actor': actor,
                    'organization_id': org_id,
                    'azure_issue_url': mapping.get('azure_issue_url'),
                    'jira_hotfix_pr': mapping.get('jira_hotfix_pr')
                }
                rows.append(row)
            
            # Use bulk COPY for high-performance insert (insightly schema, not insightly_jira)
            from repositories.bulk_copy import bulk_copy_insert
            inserted_count = bulk_copy_insert(session, 'jira_issue_git_activity_mapping', columns, rows)
            
            session.commit()
            
            return {
                "success": True,
                "inserted_count": inserted_count,
                "skipped_count": skipped_count
            }
            
        except Exception as e:
            session.rollback()
            raise Exception(f"Error importing JIRA-Git mappings: {str(e)}")
