from __future__ import annotations

from typing import Mapping, Sequence

from sqlalchemy import text
from sqlalchemy.orm import Session


PULL_REQUEST_INSERT_SQL = text(
    """
    INSERT INTO insightly.pull_request (
        id,
        organizationid,
        workspaceid,
        actualpullrequestid,
        title,
        authorid,
        createdon,
        description,
        destinationbranch,
        sourcebranch,
        firstcommitid,
        sourcecommitid,
        destinationcommitid,
        state,
        repoid,
        linesadded,
        linesremoved,
        htmllink,
        commentcount,
        commitscount,
        modifiedfilescount,
        reason,
        updatedon,
        mergecommit,
        mergedby,
        firstreviewedby,
        approvedby,
        originalmergedby,
        mergedon,
        declinedon,
        reviewedon,
        approvedon,
        firstcommittedon,
        committoopenduration,
        opentoreviewduration,
        reviewedtoapprovedduration,
        reviewedtomergedduration,
        approvedtomergedduration,
        reviewedtodeclineduration,
        opentodeclineduration,
        opentomergedduration,
        cycletimeduration,
        deploytimeduration,
        cycletimeoverflow,
        declinedby,
        remark,
        originalauthorid,
        createddate,
        modifieddate,
        originalapprovedby,
        originalfirstreviewedby,
        originaldeclinedby,
        processed,
        hotfixpr,
        reviewbranchpr,
        releasebranchpr,
        excludepr,
        flashyreviewedpr,
        jiramappingprocessed,
        labels,
        prsentiment,
        issourcebranchdeleted,
        userintegrationid,
        jiradatacollected,
        reviewcyclecount,
        autoexcludepr,
        opentofirstcommentduration,
        firstcommenttoapproved,
        estimated_storypoints,
        comment_sentiment_count,
        is_deployment_pr,
        mergetodeployduration,
        deployment_record_id,
        incident_record_id,
        is_incident_pr
    ) VALUES (
        :id,
        :organizationid,
        :workspaceid,
        :actualpullrequestid,
        :title,
        :authorid,
        :createdon,
        :description,
        :destinationbranch,
        :sourcebranch,
        :firstcommitid,
        :sourcecommitid,
        :destinationcommitid,
        :state,
        :repoid,
        :linesadded,
        :linesremoved,
        :htmllink,
        :commentcount,
        :commitscount,
        :modifiedfilescount,
        :reason,
        :updatedon,
        :mergecommit,
        :mergedby,
        :firstreviewedby,
        :approvedby,
        :originalmergedby,
        :mergedon,
        :declinedon,
        :reviewedon,
        :approvedon,
        :firstcommittedon,
        :committoopenduration,
        :opentoreviewduration,
        :reviewedtoapprovedduration,
        :reviewedtomergedduration,
        :approvedtomergedduration,
        :reviewedtodeclineduration,
        :opentodeclineduration,
        :opentomergedduration,
        :cycletimeduration,
        :deploytimeduration,
        :cycletimeoverflow,
        :declinedby,
        :remark,
        :originalauthorid,
        :createddate,
        :modifieddate,
        :originalapprovedby,
        :originalfirstreviewedby,
        :originaldeclinedby,
        :processed,
        :hotfixpr,
        :reviewbranchpr,
        :releasebranchpr,
        :excludepr,
        :flashyreviewedpr,
        :jiramappingprocessed,
        :labels,
        :prsentiment,
        :issourcebranchdeleted,
        :userintegrationid,
        :jiradatacollected,
        :reviewcyclecount,
        :autoexcludepr,
        :opentofirstcommentduration,
        :firstcommenttoapproved,
        :estimated_storypoints,
        :comment_sentiment_count,
        :is_deployment_pr,
        :mergetodeployduration,
        :deployment_record_id,
        :incident_record_id,
        :is_incident_pr
    )
    ON CONFLICT (id, organizationid)
    DO UPDATE SET
        workspaceid = EXCLUDED.workspaceid,
        actualpullrequestid = EXCLUDED.actualpullrequestid,
        title = EXCLUDED.title,
        authorid = EXCLUDED.authorid,
        createdon = EXCLUDED.createdon,
        description = EXCLUDED.description,
        destinationbranch = EXCLUDED.destinationbranch,
        sourcebranch = EXCLUDED.sourcebranch,
        firstcommitid = EXCLUDED.firstcommitid,
        sourcecommitid = EXCLUDED.sourcecommitid,
        destinationcommitid = EXCLUDED.destinationcommitid,
        state = EXCLUDED.state,
        repoid = EXCLUDED.repoid,
        linesadded = EXCLUDED.linesadded,
        linesremoved = EXCLUDED.linesremoved,
        htmllink = EXCLUDED.htmllink,
        commentcount = EXCLUDED.commentcount,
        commitscount = EXCLUDED.commitscount,
        modifiedfilescount = EXCLUDED.modifiedfilescount,
        reason = EXCLUDED.reason,
        updatedon = EXCLUDED.updatedon,
        mergecommit = EXCLUDED.mergecommit,
        mergedby = EXCLUDED.mergedby,
        firstreviewedby = EXCLUDED.firstreviewedby,
        approvedby = EXCLUDED.approvedby,
        originalmergedby = EXCLUDED.originalmergedby,
        mergedon = EXCLUDED.mergedon,
        declinedon = EXCLUDED.declinedon,
        reviewedon = EXCLUDED.reviewedon,
        approvedon = EXCLUDED.approvedon,
        firstcommittedon = EXCLUDED.firstcommittedon,
        committoopenduration = EXCLUDED.committoopenduration,
        opentoreviewduration = EXCLUDED.opentoreviewduration,
        reviewedtoapprovedduration = EXCLUDED.reviewedtoapprovedduration,
        reviewedtomergedduration = EXCLUDED.reviewedtomergedduration,
        approvedtomergedduration = EXCLUDED.approvedtomergedduration,
        reviewedtodeclineduration = EXCLUDED.reviewedtodeclineduration,
        opentodeclineduration = EXCLUDED.opentodeclineduration,
        opentomergedduration = EXCLUDED.opentomergedduration,
        cycletimeduration = EXCLUDED.cycletimeduration,
        deploytimeduration = EXCLUDED.deploytimeduration,
        cycletimeoverflow = EXCLUDED.cycletimeoverflow,
        declinedby = EXCLUDED.declinedby,
        remark = EXCLUDED.remark,
        originalauthorid = EXCLUDED.originalauthorid,
        createddate = EXCLUDED.createddate,
        originalapprovedby = EXCLUDED.originalapprovedby,
        originalfirstreviewedby = EXCLUDED.originalfirstreviewedby,
        originaldeclinedby = EXCLUDED.originaldeclinedby,
        processed = EXCLUDED.processed,
        hotfixpr = EXCLUDED.hotfixpr,
        reviewbranchpr = EXCLUDED.reviewbranchpr,
        releasebranchpr = EXCLUDED.releasebranchpr,
        excludepr = EXCLUDED.excludepr,
        flashyreviewedpr = EXCLUDED.flashyreviewedpr,
        jiramappingprocessed = EXCLUDED.jiramappingprocessed,
        labels = EXCLUDED.labels,
        prsentiment = EXCLUDED.prsentiment,
        issourcebranchdeleted = EXCLUDED.issourcebranchdeleted,
        userintegrationid = EXCLUDED.userintegrationid,
        jiradatacollected = EXCLUDED.jiradatacollected,
        reviewcyclecount = EXCLUDED.reviewcyclecount,
        opentofirstcommentduration = EXCLUDED.opentofirstcommentduration,
        firstcommenttoapproved = EXCLUDED.firstcommenttoapproved,
        autoexcludepr = EXCLUDED.autoexcludepr,
        estimated_storypoints = EXCLUDED.estimated_storypoints,
        comment_sentiment_count = EXCLUDED.comment_sentiment_count,
        is_deployment_pr = EXCLUDED.is_deployment_pr,
        mergetodeployduration = EXCLUDED.mergetodeployduration,
        deployment_record_id = EXCLUDED.deployment_record_id,
        incident_record_id = EXCLUDED.incident_record_id,
        is_incident_pr = EXCLUDED.is_incident_pr,
        modifieddate = CURRENT_TIMESTAMP
    """
)


class PullRequestRepository:
    """Handles persistence for pull request imports."""

    def bulk_upsert(
        self, session: Session, rows: Sequence[Mapping]
    ) -> int:
        if not rows:
            return 0

        session.execute(PULL_REQUEST_INSERT_SQL, rows)
        return len(rows)
