from __future__ import annotations

from typing import Mapping, Sequence

from sqlalchemy import text
from sqlalchemy.orm import Session


PULL_REQUEST_INSERT_SQL = text(
    """
    INSERT INTO insightly.pull_request (
        id,
        organizationid,
        workspaceid,
        actualpullrequestid,
        title,
        authorid,
        createdon,
        description,
        destinationbranch,
        sourcebranch,
        firstcommitid,
        sourcecommitid,
        destinationcommitid,
        state,
        repoid,
        linesadded,
        linesremoved,
        htmllink,
        commentcount,
        commitscount,
        modifiedfilescount,
        updatedon,
        mergecommit,
        mergedby,
        approvedby,
        mergedon,
        declinedon,
        approvedon,
        firstcommittedon,
        committoopenduration,
        opentoreviewduration,
        reviewedtoapprovedduration,
        reviewedtomergedduration,
        approvedtomergedduration,
        reviewedtodeclineduration,
        opentodeclineduration,
        opentomergedduration,
        cycletimeduration,
        deploytimeduration,
        cycletimeoverflow,
        declinedby,
        remark,
        originalauthorid,
        originalapprovedby,
        originalfirstreviewedby,
        originaldeclinedby,
        processed,
        hotfixpr,
        reviewbranchpr,
        releasebranchpr,
        excludepr,
        flashyreviewedpr,
        userintegrationid,
        reviewcyclecount,
        opentofirstcommentduration,
        firstcommenttoapproved
    ) VALUES (
        :id,
        :organizationid,
        :workspaceid,
        :actualpullrequestid,
        :title,
        :authorid,
        :createdon,
        :description,
        :destinationbranch,
        :sourcebranch,
        :firstcommitid,
        :sourcecommitid,
        :destinationcommitid,
        :state,
        :repoid,
        :linesadded,
        :linesremoved,
        :htmllink,
        :commentcount,
        :commitscount,
        :modifiedfilescount,
        :updatedon,
        :mergecommit,
        :mergedby,
        :approvedby,
        :mergedon,
        :declinedon,
        :approvedon,
        :firstcommittedon,
        :committoopenduration,
        :opentoreviewduration,
        :reviewedtoapprovedduration,
        :reviewedtomergedduration,
        :approvedtomergedduration,
        :reviewedtodeclineduration,
        :opentodeclineduration,
        :opentomergedduration,
        :cycletimeduration,
        :deploytimeduration,
        :cycletimeoverflow,
        :declinedby,
        :remark,
        :originalauthorid,
        :originalapprovedby,
        :originalfirstreviewedby,
        :originaldeclinedby,
        :processed,
        :hotfixpr,
        :reviewbranchpr,
        :releasebranchpr,
        :excludepr,
        :flashyreviewedpr,
        :userintegrationid,
        :reviewcyclecount,
        :opentofirstcommentduration,
        :firstcommenttoapproved
    )
    ON CONFLICT (id, organizationid)
    DO UPDATE SET
        workspaceid = EXCLUDED.workspaceid,
        actualpullrequestid = EXCLUDED.actualpullrequestid,
        title = EXCLUDED.title,
        authorid = EXCLUDED.authorid,
        createdon = EXCLUDED.createdon,
        description = EXCLUDED.description,
        destinationbranch = EXCLUDED.destinationbranch,
        sourcebranch = EXCLUDED.sourcebranch,
        firstcommitid = EXCLUDED.firstcommitid,
        sourcecommitid = EXCLUDED.sourcecommitid,
        destinationcommitid = EXCLUDED.destinationcommitid,
        state = EXCLUDED.state,
        repoid = EXCLUDED.repoid,
        linesadded = EXCLUDED.linesadded,
        linesremoved = EXCLUDED.linesremoved,
        htmllink = EXCLUDED.htmllink,
        commentcount = EXCLUDED.commentcount,
        commitscount = EXCLUDED.commitscount,
        modifiedfilescount = EXCLUDED.modifiedfilescount,
        updatedon = EXCLUDED.updatedon,
        mergecommit = EXCLUDED.mergecommit,
        mergedby = EXCLUDED.mergedby,
        approvedby = EXCLUDED.approvedby,
        mergedon = EXCLUDED.mergedon,
        declinedon = EXCLUDED.declinedon,
        approvedon = EXCLUDED.approvedon,
        firstcommittedon = EXCLUDED.firstcommittedon,
        committoopenduration = EXCLUDED.committoopenduration,
        opentoreviewduration = EXCLUDED.opentoreviewduration,
        reviewedtoapprovedduration = EXCLUDED.reviewedtoapprovedduration,
        reviewedtomergedduration = EXCLUDED.reviewedtomergedduration,
        approvedtomergedduration = EXCLUDED.approvedtomergedduration,
        reviewedtodeclineduration = EXCLUDED.reviewedtodeclineduration,
        opentodeclineduration = EXCLUDED.opentodeclineduration,
        opentomergedduration = EXCLUDED.opentomergedduration,
        cycletimeduration = EXCLUDED.cycletimeduration,
        deploytimeduration = EXCLUDED.deploytimeduration,
        cycletimeoverflow = EXCLUDED.cycletimeoverflow,
        declinedby = EXCLUDED.declinedby,
        remark = EXCLUDED.remark,
        originalauthorid = EXCLUDED.originalauthorid,
        originalapprovedby = EXCLUDED.originalapprovedby,
        originalfirstreviewedby = EXCLUDED.originalfirstreviewedby,
        originaldeclinedby = EXCLUDED.originaldeclinedby,
        processed = EXCLUDED.processed,
        hotfixpr = EXCLUDED.hotfixpr,
        reviewbranchpr = EXCLUDED.reviewbranchpr,
        releasebranchpr = EXCLUDED.releasebranchpr,
        excludepr = EXCLUDED.excludepr,
        flashyreviewedpr = EXCLUDED.flashyreviewedpr,
        userintegrationid = EXCLUDED.userintegrationid,
        reviewcyclecount = EXCLUDED.reviewcyclecount,
        opentofirstcommentduration = EXCLUDED.opentofirstcommentduration,
        firstcommenttoapproved = EXCLUDED.firstcommenttoapproved,
        modifieddate = CURRENT_TIMESTAMP
    """
)


class PullRequestRepository:
    """Handles persistence for pull request imports."""

    def bulk_upsert(
        self, session: Session, rows: Sequence[Mapping]
    ) -> int:
        if not rows:
            return 0

        session.execute(PULL_REQUEST_INSERT_SQL, rows)
        return len(rows)
