from __future__ import annotations

from datetime import date
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class MetricScope(BaseModel):
    organization_id: int = Field(..., description="Organization ID")
    repo_id: Optional[int] = Field(None, description="Repo ID to scope changes")
    team_id: Optional[int] = Field(None, description="Team ID to scope changes")
    author_ids: Optional[List[int]] = Field(None, description="Limit to author IDs")
    start_date: date = Field(..., description="Inclusive start date")
    end_date: date = Field(..., description="Exclusive end date")


class MetricTarget(BaseModel):
    mode: str = Field(..., description="absolute or delta")
    value: float = Field(..., description="Target value or delta")
    unit: str = Field(..., description="count, minutes, percent")


class MetricChangeRequest(BaseModel):
    metric_id: str
    action: str
    scope: MetricScope
    target: Optional[MetricTarget] = None
    options: Dict[str, Any] = Field(default_factory=dict)


class MetricPoint(BaseModel):
    period: str
    value: float


class MetricSnapshot(BaseModel):
    metric_id: str
    scope: MetricScope
    total_value: float
    by_period: List[MetricPoint]


class ChangePlan(BaseModel):
    plan_id: str
    summary: str
    sql_statements: List[str]
    sql_params: List[Dict[str, Any]]
    before_rows: List[Dict[str, Any]]
    expected: Dict[str, Any]
    warnings: List[str] = Field(default_factory=list)


class ChangeResult(BaseModel):
    plan_id: str
    applied: bool
    rows_affected: int
    warnings: List[str] = Field(default_factory=list)


class EligibilityRequest(BaseModel):
    metric_id: str
    action: Optional[str] = None
    organization_id: int
    repo_id: Optional[int] = None
    team_id: Optional[int] = None
    author_ids: Optional[List[int]] = None
    start_date: date
    end_date: date


class EligibleEntity(BaseModel):
    id: int
    count: int
    label: Optional[str] = None


class EligibilityResponse(BaseModel):
    metric_id: str
    repos: List[EligibleEntity] = Field(default_factory=list)
    teams: List[EligibleEntity] = Field(default_factory=list)
    authors: List[EligibleEntity] = Field(default_factory=list)


class EligibilitySummaryRequest(BaseModel):
    metric_id: str
    action: str
    scope: MetricScope
    options: Dict[str, Any] = Field(default_factory=dict)


class EligibilitySummaryPoint(BaseModel):
    period: str
    eligible_count: int


class EligibilitySummaryResponse(BaseModel):
    metric_id: str
    action: str
    by_period: List[EligibilitySummaryPoint] = Field(default_factory=list)


class MetricImpact(BaseModel):
    metric_id: str
    label: str
    before: MetricSnapshot
    after: MetricSnapshot


class ImpactResponse(BaseModel):
    metric_id: str
    affected: List[MetricImpact]
    plan: ChangePlan


class AIChangeRequest(BaseModel):
    """Request for AI-driven metric change."""
    user_intent: str = Field(..., description="Natural language description of desired change")
    scope: MetricScope = Field(..., description="Scope for the change")
    context: Optional[Dict[str, Any]] = Field(None, description="Additional context for the AI")


class AIChangePlan(BaseModel):
    """Plan generated by AI for metric change."""
    plan_id: str
    user_intent: str
    request_type: str = Field(..., description="Type of request (commit_volume, pr_review, etc.)")
    sql_statements: List[str]
    sql_params: List[Dict[str, Any]]
    affected_metrics: List[str] = Field(default_factory=list)
    validation_checks: List[str] = Field(default_factory=list)
    reasoning: str = Field(..., description="AI's explanation of the approach")
    estimated_rows: int = Field(0, description="Estimated number of rows affected")
    warnings: List[str] = Field(default_factory=list)


class AIChangeResult(BaseModel):
    """Result of applying an AI-driven change."""
    plan_id: str
    applied: bool
    rows_affected: int
    affected_metrics: List[str]
    warnings: List[str] = Field(default_factory=list)
    reasoning: str
