from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

import pandas as pd
from fastapi import APIRouter, Depends, File, HTTPException, Query, UploadFile, status
from sqlalchemy.orm import Session

from db.session import get_db_session
from repositories.change_requests_repository import ChangeRequestsRepository
from schemas.change_requests import (
    DATETIME_FIELDS,
    INT_FIELDS,
    REQUIRED_FIELDS,
    ChangeRequestsImportResponse,
)
from utils.csv_loader import read_uploaded_csv
from utils.parsers import coerce_datetime, coerce_int, sanitize_value

router = APIRouter(prefix="/change-requests", tags=["change-requests"])
_repository = ChangeRequestsRepository()

CHANGE_REQUESTS_COLUMNS = [
    "event_id",
    "event_type",
    "outage_incident_number",
    "createddate",
    "modifieddate",
    "start_date",
    "end_date",
    "assignment_group",
    "caused_by_azdo_item",
    "caused_by_change",
    "team_id",
    "close_code",
    "duration",
    "authorid",
    "repoid",
]

DEFAULT_CHANGE_REQUESTS_VALUES = {
    "outage_incident_number": None,
    "assignment_group": None,
    "caused_by_azdo_item": None,
    "caused_by_change": None,
    "close_code": None,
    "duration": None,
}


def _normalize_csv_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize CSV column names to match our expected format"""
    normalized = {}
    for original in df.columns:
        key = original.strip().lower().replace(" ", "_").replace("-", "_")
        normalized[original] = key
    return df.rename(columns=normalized)


def _prepare_rows(df: pd.DataFrame) -> List[Dict]:
    # Columns that will be injected from query parameters
    INJECTED_COLUMNS = {"organization_id"}
    # Skip 'id' column - it will be auto-generated by the database
    SKIPPED_COLUMNS = {"id"}

    df = _normalize_csv_columns(df)

    missing_columns = [col for col in REQUIRED_FIELDS if col not in df.columns]
    if missing_columns:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"CSV missing required columns: {', '.join(missing_columns)}",
        )

    prepared: List[Dict] = []

    records = df.to_dict(orient="records")
    for idx, record in enumerate(records, start=1):
        try:
            row: Dict[str, Any] = {}
            for column in CHANGE_REQUESTS_COLUMNS:
                # Skip columns that will be injected from query parameters or auto-generated
                if column in INJECTED_COLUMNS or column in SKIPPED_COLUMNS:
                    continue

                raw_value = sanitize_value(
                    record.get(column, DEFAULT_CHANGE_REQUESTS_VALUES.get(column))
                )

                if column in INT_FIELDS and raw_value is not None:
                    raw_value = coerce_int(raw_value, strict=False)
                elif column in DATETIME_FIELDS and raw_value is not None:
                    raw_value = coerce_datetime(raw_value, strict=False)

                row[column] = raw_value

            for field in REQUIRED_FIELDS:
                if row.get(field) is None:
                    raise ValueError(f"Missing required value for '{field}'")

            now = datetime.utcnow()
            row["createddate"] = row.get("createddate") or now
            row["modifieddate"] = row.get("modifieddate") or now

            prepared.append(row)
        except ValueError:
            continue

    return prepared


@router.post(
    "/csv",
    status_code=status.HTTP_201_CREATED,
    summary="Import change requests from a CSV file",
    response_model=ChangeRequestsImportResponse,
)
async def import_change_requests_from_csv(
    organization_id: int = Query(..., description="Organization ID"),
    file: UploadFile = File(...),
    session: Session = Depends(get_db_session),
) -> ChangeRequestsImportResponse:
    df = await read_uploaded_csv(file)

    rows = _prepare_rows(df)
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No valid change request rows found in CSV.",
        )

    # Inject organization_id into each row
    for row in rows:
        row["organization_id"] = organization_id

    inserted = _repository.bulk_insert(session, rows)
    return ChangeRequestsImportResponse(
        rows_received=len(df),
        rows_inserted=len(inserted),
        rows_skipped=len(df) - len(inserted),
        organization_id=organization_id,
    )
