from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

import pandas as pd
from fastapi import APIRouter, Depends, File, HTTPException, Query, UploadFile, status
from sqlalchemy.orm import Session

from db.session import get_db_session
from repositories.deployment_frequency_repository import DeploymentFrequencyRepository
from schemas.deployment_frequency import (
    DATETIME_FIELDS,
    INT_FIELDS,
    REQUIRED_FIELDS,
    DeploymentFrequencyImportResponse,
)
from utils.csv_loader import read_uploaded_csv
from utils.parsers import coerce_datetime, coerce_int, sanitize_value

router = APIRouter(prefix="/deployment-frequency", tags=["deployment-frequency"])
_repository = DeploymentFrequencyRepository()

DEPLOYMENT_FREQUENCY_COLUMNS = [
    "deployment_record_id",
    "start_date",
    "end_date",
    "environment_id",
    "owner_id",
    "result",
    "pipeline_id",
    "created_date",
    "modified_date",
    "authorid",
    "originalauthorid",
    "repoid",
    "team_id",
    "release_date",
]

DEFAULT_DEPLOYMENT_FREQUENCY_VALUES = {
    "environment_id": None,
    "owner_id": None,
    "pipeline_id": None,
    "authorid": None,
    "originalauthorid": None,
    "repoid": None,
    "team_id": None,
    "release_date": None,
}


def _normalize_csv_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize CSV column names to match our expected format"""
    normalized = {}
    for original in df.columns:
        key = original.strip().lower().replace(" ", "_").replace("-", "_")
        normalized[original] = key
    return df.rename(columns=normalized)


def _prepare_rows(df: pd.DataFrame) -> List[Dict]:
    # Columns that will be injected from query parameters
    INJECTED_COLUMNS = {"organization_id", "user_integration_id"}
    # Skip 'id' column - it will be auto-generated by the database
    SKIPPED_COLUMNS = {"id"}

    df = _normalize_csv_columns(df)

    missing_columns = [col for col in REQUIRED_FIELDS if col not in df.columns]
    if missing_columns:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"CSV missing required columns: {', '.join(missing_columns)}",
        )

    prepared: List[Dict] = []

    records = df.to_dict(orient="records")
    for idx, record in enumerate(records, start=1):
        try:
            row: Dict[str, Any] = {}
            for column in DEPLOYMENT_FREQUENCY_COLUMNS:
                # Skip columns that will be injected from query parameters or auto-generated
                if column in INJECTED_COLUMNS or column in SKIPPED_COLUMNS:
                    continue

                raw_value = sanitize_value(
                    record.get(column, DEFAULT_DEPLOYMENT_FREQUENCY_VALUES.get(column))
                )

                if column in INT_FIELDS and raw_value is not None:
                    raw_value = coerce_int(raw_value, strict=False)
                elif column in DATETIME_FIELDS and raw_value is not None:
                    raw_value = coerce_datetime(raw_value, strict=False)

                row[column] = raw_value

            for field in REQUIRED_FIELDS:
                if row.get(field) is None:
                    raise ValueError(f"Missing required value for '{field}'")

            now = datetime.utcnow()
            row["created_date"] = row.get("created_date") or now
            row["modified_date"] = row.get("modified_date") or now

            prepared.append(row)
        except ValueError:
            continue

    return prepared


@router.post(
    "/csv",
    status_code=status.HTTP_201_CREATED,
    summary="Import deployment frequency from a CSV file",
    response_model=DeploymentFrequencyImportResponse,
)
async def import_deployment_frequency_from_csv(
    organization_id: int = Query(..., description="Organization ID"),
    user_integration_id: int = Query(..., description="User Integration ID"),
    file: UploadFile = File(...),
    session: Session = Depends(get_db_session),
) -> DeploymentFrequencyImportResponse:
    df = await read_uploaded_csv(file)

    rows = _prepare_rows(df)
    if not rows:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No valid deployment frequency rows found in CSV.",
        )

    # Inject organization_id and user_integration_id into each row
    for row in rows:
        row["organization_id"] = organization_id
        row["user_integration_id"] = user_integration_id

    inserted = _repository.bulk_insert(session, rows)
    # bulk_insert now returns [{"inserted_count": N}] due to COPY optimization
    inserted_count = inserted[0].get("inserted_count", 0) if inserted else 0
    return DeploymentFrequencyImportResponse(
        rows_received=len(df),
        rows_inserted=inserted_count,
        rows_skipped=len(df) - len(rows),  # rows that failed validation
        organization_id=organization_id,
        user_integration_id=user_integration_id,
    )
