from __future__ import annotations

from typing import Any, Dict, List, Tuple

import pandas as pd
from fastapi import APIRouter, Depends, File, HTTPException, Query, UploadFile, status
from sqlalchemy.orm import Session

from db.session import get_db_session
from repositories.pull_request_repository import PullRequestRepository
from schemas.pull_request_import import (
    BOOL_COLUMNS,
    EXPECTED_COLUMNS,
    FLOAT_COLUMNS,
    INT_COLUMNS,
    PullRequestImportResponse,
    REQUIRED_COLUMNS,
    TIMESTAMP_COLUMNS,
)
from utils.csv_loader import read_uploaded_csv
from utils.parsers import (
    clean_text,
    coerce_bool,
    coerce_datetime,
    coerce_float,
    coerce_int,
)

router = APIRouter(prefix="/pull-request-import", tags=["pull-request-import"])

_repository = PullRequestRepository()


@router.get(
    "/check",
    status_code=status.HTTP_200_OK,
    summary="Check if pull_request table exists and count PRs for an organization",
)
def check_pull_request_table(
    organization_id: int = Query(..., description="Organization ID"),
    session: Session = Depends(get_db_session),
):
    table_exists, pr_count = _repository.check_table_and_count_by_org(
        session, organization_id=organization_id
    )
    
    return {
        "table_exists": table_exists,
        "organization_id": organization_id,
        "pull_requests_count": pr_count,
    }


def _normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    alias_map = {
        "firstcommenttoapprovedduration": "firstcommenttoapproved",
        "html_link": "htmllink",
    }

    normalized = {}
    for original in df.columns:
        key = original.strip().lower().replace(" ", "").replace("-", "")
        replacement = alias_map.get(key, key)
        normalized[original] = replacement

    return df.rename(columns=normalized)


def _prepare_payloads(df: pd.DataFrame) -> Tuple[List[Dict], int, Dict[str, int]]:
    # Columns that will be injected from query parameters, not from CSV
    INJECTED_COLUMNS = {"organizationid", "userintegrationid"}
    # Skip 'id' column - it will be auto-generated by the database
    SKIPPED_COLUMNS = {"id"}
    
    df = _normalize_columns(df)

    # Check for missing columns, but exclude the injected and skipped columns
    columns_to_check = [col for col in EXPECTED_COLUMNS if col not in INJECTED_COLUMNS and col not in SKIPPED_COLUMNS]
    missing = [col for col in columns_to_check if col not in df.columns]
    if missing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"CSV missing expected columns: {', '.join(missing)}",
        )

    # Check required columns (excluding organizationid which will be injected)
    required_to_check = REQUIRED_COLUMNS - INJECTED_COLUMNS
    if any(col not in df.columns for col in required_to_check):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="CSV missing required pull request identifiers.",
        )

    # Drop duplicates based on the unique constraint (actualpullrequestid, repoid, organizationid)
    filtered = df.drop_duplicates(
        subset=["actualpullrequestid", "repoid"]
    ).dropna(subset=list(REQUIRED_COLUMNS))

    payloads: List[Dict] = []
    conversion_errors = 0
    missing_required: Dict[str, int] = {}

    for row in filtered.itertuples(index=False):
        try:
            payload = {}
            for column in EXPECTED_COLUMNS:
                # Skip columns that will be injected or auto-generated
                if column in INJECTED_COLUMNS or column in SKIPPED_COLUMNS:
                    continue
                    
                value = getattr(row, column)
                if column in TIMESTAMP_COLUMNS:
                    payload[column] = coerce_datetime(value)
                elif column in INT_COLUMNS:
                    payload[column] = coerce_int(value)
                elif column in FLOAT_COLUMNS:
                    payload[column] = coerce_float(value)
                elif column in BOOL_COLUMNS:
                    payload[column] = coerce_bool(value)
                else:
                    payload[column] = clean_text(value)

            row_missing = [
                required for required in REQUIRED_COLUMNS if payload.get(required) is None
            ]
            if row_missing:
                for column in row_missing:
                    missing_required[column] = missing_required.get(column, 0) + 1
                continue

            payloads.append(payload)
        except Exception:
            conversion_errors += 1
            continue

    return payloads, conversion_errors, missing_required


@router.post(
    "/csv",
    status_code=status.HTTP_201_CREATED,
    summary="Import pull requests from a CSV file",
    response_model=PullRequestImportResponse,
)
async def import_pull_requests(
    organization_id: int = Query(..., description="Organization ID"),
    user_integration_id: int = Query(..., description="User Integration ID"),
    file: UploadFile = File(...),
    session: Session = Depends(get_db_session),
) -> PullRequestImportResponse:
    df = await read_uploaded_csv(file)

    payloads, conversion_errors, missing_required = _prepare_payloads(df)
    if not payloads:
        detail = "No valid pull request rows found in CSV."
        if missing_required:
            columns = ", ".join(
                f"{column} ({count} rows)" for column, count in sorted(missing_required.items())
            )
            detail = f"{detail} Missing required values for: {columns}."
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=detail,
        )

    # Inject organizationid and userintegrationid into each payload
    for payload in payloads:
        payload["organizationid"] = organization_id
        payload["userintegrationid"] = user_integration_id

    inserted = _repository.bulk_upsert(session, payloads)

    return PullRequestImportResponse(
        rows_received=len(df),
        rows_inserted=inserted,
        rows_skipped=conversion_errors + (len(df) - len(payloads)),
    )
