from pydantic import BaseModel


class PullRequestImportResponse(BaseModel):
    rows_received: int
    rows_inserted: int
    rows_skipped: int


EXPECTED_COLUMNS = [
    "id",
    "organizationid",
    "workspaceid",
    "actualpullrequestid",
    "title",
    "authorid",
    "createdon",
    "description",
    "destinationbranch",
    "sourcebranch",
    "firstcommitid",
    "sourcecommitid",
    "destinationcommitid",
    "state",
    "repoid",
    "linesadded",
    "linesremoved",
    "htmllink",
    "commentcount",
    "commitscount",
    "modifiedfilescount",
    "reason",
    "updatedon",
    "mergecommit",
    "mergedby",
    "firstreviewedby",
    "approvedby",
    "originalmergedby",
    "mergedon",
    "declinedon",
    "reviewedon",
    "approvedon",
    "firstcommittedon",
    "committoopenduration",
    "opentoreviewduration",
    "reviewedtoapprovedduration",
    "reviewedtomergedduration",
    "approvedtomergedduration",
    "reviewedtodeclineduration",
    "opentodeclineduration",
    "opentomergedduration",
    "cycletimeduration",
    "deploytimeduration",
    "cycletimeoverflow",
    "declinedby",
    "remark",
    "originalauthorid",
    "createddate",
    "modifieddate",
    "originalapprovedby",
    "originalfirstreviewedby",
    "originaldeclinedby",
    "processed",
    "hotfixpr",
    "reviewbranchpr",
    "releasebranchpr",
    "excludepr",
    "flashyreviewedpr",
    "jiramappingprocessed",
    "labels",
    "prsentiment",
    "issourcebranchdeleted",
    "userintegrationid",
    "jiradatacollected",
    "reviewcyclecount",
    "autoexcludepr",
    "opentofirstcommentduration",
    "firstcommenttoapproved",
    "estimated_storypoints",
    "comment_sentiment_count",
    "is_deployment_pr",
    "mergetodeployduration",
    "deployment_record_id",
    "incident_record_id",
    "is_incident_pr",
]

REQUIRED_COLUMNS = {
    "id",
    "actualpullrequestid",
    "authorid",
    "createdon",
    "repoid",
    "organizationid",
    "workspaceid",
}

TIMESTAMP_COLUMNS = {
    "createdon",
    "updatedon",
    "mergedon",
    "declinedon",
    "reviewedon",
    "approvedon",
    "firstcommittedon",
    "createddate",
    "modifieddate",
}

FLOAT_COLUMNS = {
    "committoopenduration",
    "opentoreviewduration",
    "reviewedtoapprovedduration",
    "reviewedtomergedduration",
    "approvedtomergedduration",
    "reviewedtodeclineduration",
    "opentodeclineduration",
    "opentomergedduration",
    "cycletimeduration",
    "deploytimeduration",
    "opentofirstcommentduration",
    "firstcommenttoapproved",
}

INT_COLUMNS = {
    "id",
    "organizationid",
    "workspaceid",
    "actualpullrequestid",
    "authorid",
    "repoid",
    "linesadded",
    "linesremoved",
    "commentcount",
    "commitscount",
    "modifiedfilescount",
    "mergedby",
    "firstreviewedby",
    "approvedby",
    "originalmergedby",
    "declinedby",
    "originalauthorid",
    "originalapprovedby",
    "originalfirstreviewedby",
    "originaldeclinedby",
    "userintegrationid",
    "reviewcyclecount",
    "estimated_storypoints",
    "comment_sentiment_count",
    "mergetodeployduration",
    "deployment_record_id",
    "incident_record_id",
}

BOOL_COLUMNS = {
    "cycletimeoverflow",
    "processed",
    "hotfixpr",
    "reviewbranchpr",
    "releasebranchpr",
    "excludepr",
    "flashyreviewedpr",
    "jiramappingprocessed",
    "issourcebranchdeleted",
    "jiradatacollected",
    "autoexcludepr",
    "is_deployment_pr",
    "is_incident_pr",
}
